var userNameCookie = "name"
var passwordCookie = "password"
var isLoginCookie = "isLogin"

var mainPageUrl = "../shrouk/html/index.html"
var loginPage = "../login.html"
var memoryGamePage = "../momery_game.html"
var hangmanGamePage = "../hasan/main.html"
var tickTackGamePage = "../ashraf/tic_tac_toe_game/index.html"
var reactionGamePage = "../ashraf/Reaction_Game/index.html"
var typingGamePage = "../shrouk/html/typing.html"